name: Bun and Android Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: 🏗 Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.2"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: bun install

      - name: Setup EAS
        run: bun i eas-cli -g

      - name: Run lint
        run: bun lint

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Android
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --local --platform android --non-interactive --profile preview --output ${{ github.workspace }}/app-release.apk

      - name: Build iOS
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --local --platform ios --non-interactive --profile preview --output ${{ github.workspace }}/app-release.ipa

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-android
          path: ${{ github.workspace }}/app-release.apk

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-ios
          path: ${{ github.workspace }}/app-release.ipa

      - name: Install ios-uploader
        run: bun install -g ios-uploader

      - name: Upload ipa to TestFlight
        run: ios-uploader upload -u ${{ secrets.APPLE_ID }} -p ${{ secrets.APPLE_PASSWORD }} -f ${{ github.workspace }}/app-release.ipa
